package com.packt.jdeveloper.cookbook.hr.components.model.application;

import com.packt.jdeveloper.cookbook.hr.components.model.application.common.HrComponentsAppModule;
import com.packt.jdeveloper.cookbook.hr.components.model.view.EmployeesImpl;
import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtApplicationModuleImpl;
import com.packt.jdeveloper.cookbook.shared.bc.extensions.ExtViewObjectImpl;

import oracle.jbo.server.ViewLinkImpl;

import oracle.jbo.domain.Number;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 03 18:14:48 EST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrComponentsAppModuleImpl extends ExtApplicationModuleImpl implements HrComponentsAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HrComponentsAppModuleImpl() {
    }

    /**
     * Container's getter for Departments1.
     * @return Departments1
     */
    public ExtViewObjectImpl getDepartments() {
        return (ExtViewObjectImpl)findViewObject("Departments");
    }

    /**
     * Container's getter for Employees1.
     * @return Employees1
     */
    public EmployeesImpl getEmployees() {
        return (EmployeesImpl)findViewObject("Employees");
    }

    /**
     * Container's getter for Employees2.
     * @return Employees2
     */
    public EmployeesImpl getEmployees2() {
        return (EmployeesImpl)findViewObject("Employees2");
    }

    /**
     * Container's getter for Departments2.
     * @return Departments2
     */
    public ExtViewObjectImpl getDepartments2() {
        return (ExtViewObjectImpl)findViewObject("Departments2");
    }

    /**
     * Container's getter for Employees3.
     * @return Employees3
     */
    public EmployeesImpl getEmployees3() {
        return (EmployeesImpl)findViewObject("Employees3");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpManagerFkLink1");
    }

    /**
     * Container's getter for DeptMgrFkLink1.
     * @return DeptMgrFkLink1
     */
    public ViewLinkImpl getDeptMgrFkLink1() {
        return (ViewLinkImpl)findViewLink("DeptMgrFkLink1");
    }

    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpDeptFkLink1");
    }
    
     public void adjustCommission(Number commissionPctAdjustment) { 
         // execute the Employees View object query to create a rowset 
         this.getEmployees().executeQuery();
        // adjust the employees commission 
        this.getEmployees().adjustCommission(commissionPctAdjustment);
    }
}
