package com.packt.jdeveloper.cookbook.hr.components.model.application.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 03 18:21:32 EST 2014
// ---------------------------------------------------------------------
public interface HrComponentsAppModule extends ApplicationModule {
    void adjustCommission(Number commissionPctAdjustment);
}
