package com.packt.jdeveloper.cookbook.shared.bc.test.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Oct 26 19:55:52 EDT 2014
// ---------------------------------------------------------------------
public interface HrAppModule extends ApplicationModule {
    void testSQLProcedure();
}
