package com.packt.jdeveloper.cookbook.hr.components.model.view.client;

import com.packt.jdeveloper.cookbook.hr.components.model.view.common.Employees;

import oracle.jbo.client.remote.ViewUsageImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 03 18:12:33 EST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesClient extends ViewUsageImpl implements Employees {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesClient() {
    }

    public void adjustCommission(Number commissionPctAdjustment) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"adjustCommission",new String [] {"oracle.jbo.domain.Number"},new Object[] {commissionPctAdjustment});
        return;
    }
}
