package com.packt.jdeveloper.cookbook.hr.components.model.application.client;

import com.packt.jdeveloper.cookbook.hr.components.model.application.common.HrComponentsAppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 03 18:21:32 EST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrComponentsAppModuleClient extends ApplicationModuleImpl implements HrComponentsAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HrComponentsAppModuleClient() {
    }

    public void adjustCommission(Number commissionPctAdjustment) {
        Object _ret =
            this.riInvokeExportedMethod(this,"adjustCommission",new String [] {"oracle.jbo.domain.Number"},new Object[] {commissionPctAdjustment});
        return;
    }
}
