package com.packt.jdeveloper.cookbook.hr.components.model.view.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 03 18:12:33 EST 2014
// ---------------------------------------------------------------------
public interface Employees extends ViewObject {
    void adjustCommission(Number commissionPctAdjustment);
}
